/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Test_display
  (JNIEnv *, jclass);

/*
 * Class:     Test
 * Method:    increment
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Test_increment
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
