/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_fhnw_prcpp_Matrix */

#ifndef _Included_ch_fhnw_prcpp_Matrix
#define _Included_ch_fhnw_prcpp_Matrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_fhnw_prcpp_Matrix
 * Method:    powerC
 * Signature: ([D[DII)V
 */
JNIEXPORT void JNICALL Java_ch_fhnw_prcpp_Matrix_powerC
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     ch_fhnw_prcpp_Matrix
 * Method:    multiplyC
 * Signature: ([D[D[DIII)V
 */
JNIEXPORT void JNICALL Java_ch_fhnw_prcpp_Matrix_multiplyC
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
